require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScholarshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Scholarship. As you add validations to Scholarship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all scholarships as @scholarships" do
      scholarship = Scholarship.create! valid_attributes
      get :index
      assigns(:scholarships).should eq([scholarship])
    end
  end

  describe "GET show" do
    it "assigns the requested scholarship as @scholarship" do
      scholarship = Scholarship.create! valid_attributes
      get :show, :id => scholarship.id.to_s
      assigns(:scholarship).should eq(scholarship)
    end
  end

  describe "GET new" do
    it "assigns a new scholarship as @scholarship" do
      get :new
      assigns(:scholarship).should be_a_new(Scholarship)
    end
  end

  describe "GET edit" do
    it "assigns the requested scholarship as @scholarship" do
      scholarship = Scholarship.create! valid_attributes
      get :edit, :id => scholarship.id.to_s
      assigns(:scholarship).should eq(scholarship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Scholarship" do
        expect {
          post :create, :scholarship => valid_attributes
        }.to change(Scholarship, :count).by(1)
      end

      it "assigns a newly created scholarship as @scholarship" do
        post :create, :scholarship => valid_attributes
        assigns(:scholarship).should be_a(Scholarship)
        assigns(:scholarship).should be_persisted
      end

      it "redirects to the created scholarship" do
        post :create, :scholarship => valid_attributes
        response.should redirect_to(Scholarship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scholarship as @scholarship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarship.any_instance.stub(:save).and_return(false)
        post :create, :scholarship => {}
        assigns(:scholarship).should be_a_new(Scholarship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarship.any_instance.stub(:save).and_return(false)
        post :create, :scholarship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scholarship" do
        scholarship = Scholarship.create! valid_attributes
        # Assuming there are no other scholarships in the database, this
        # specifies that the Scholarship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Scholarship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => scholarship.id, :scholarship => {'these' => 'params'}
      end

      it "assigns the requested scholarship as @scholarship" do
        scholarship = Scholarship.create! valid_attributes
        put :update, :id => scholarship.id, :scholarship => valid_attributes
        assigns(:scholarship).should eq(scholarship)
      end

      it "redirects to the scholarship" do
        scholarship = Scholarship.create! valid_attributes
        put :update, :id => scholarship.id, :scholarship => valid_attributes
        response.should redirect_to(scholarship)
      end
    end

    describe "with invalid params" do
      it "assigns the scholarship as @scholarship" do
        scholarship = Scholarship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarship.any_instance.stub(:save).and_return(false)
        put :update, :id => scholarship.id.to_s, :scholarship => {}
        assigns(:scholarship).should eq(scholarship)
      end

      it "re-renders the 'edit' template" do
        scholarship = Scholarship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarship.any_instance.stub(:save).and_return(false)
        put :update, :id => scholarship.id.to_s, :scholarship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scholarship" do
      scholarship = Scholarship.create! valid_attributes
      expect {
        delete :destroy, :id => scholarship.id.to_s
      }.to change(Scholarship, :count).by(-1)
    end

    it "redirects to the scholarships list" do
      scholarship = Scholarship.create! valid_attributes
      delete :destroy, :id => scholarship.id.to_s
      response.should redirect_to(scholarships_url)
    end
  end

end
